/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ed_er_8220195_8220147;

import org.junit.jupiter.api.Test;

import App.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
